### ISSUE TITLE
Why NodeJS 0.3.0?

### ISSUE THREAD

**Issue by wadey** [maritz/node-sprintf#1]
The package.json file says that node >= 0.3.0 is required. Why is this necessary? 0.3.0 is an unstable release, the latest stable release of node is 0.2.4.

**Comment by maritz** [comment]
The reason is pure laziness on my part, since I'm currently only developing under 0.3.0. If you can confirm that it works with 0.2.4 I'll change it to that. (shouldn't cause any problems though)

**Comment by wadey** [comment]
I've been using it today with 0.2.4 and I haven't had any problems. I think changing the dependency to 0.2.4 shouldn't cause any problems.

Thanks for setting up the repo and making the adjustments for node!

**Comment by maritz** [comment]
Okay, I updated the code. Can't access npm at work though, I'll publish sometime in the next 20 hours.

**Comment by maritz** [comment]
Wow, that took me entirely too long.

Sorry for the delay, it's updated in npm now.
