### ISSUE TITLE
npm code does not match github code

### ISSUE THREAD

**Issue by erelsgl** [maritz/node-sprintf#12]
When I install from npm, I still get the version which throws mere strings:

"throw(sprintf('[sprintf] property "%s" does not exist', match[2][k]));"

Although in GitHub it was corrected over 2 years ago:

https://github.com/maritz/node-sprintf/pull/5

**Comment by maritz** [comment]
Sorry about that. Completely forgot I hadn't published it because of an error in npm back then.

I'm still/again getting errors trying to publish the current code. I'm on it though.

**Comment by maritz** [comment]
https://github.com/isaacs/npm/issues/3842 Let's hope I don't forget about it this time. :/

**Comment by maritz** [comment]
Fixed.
