### ISSUE TITLE
Unnecessary require

### ISSUE THREAD

**Issue by chris-l** [maritz/node-sprintf#15]
Hi, I just noticed the line:
`var util = require('util');`
But it seems that var `util` is never really used. Is necessary that `require`?

(not that it causes any problems as far as I know)

**Comment by tikonen** [comment]
It's just left-over from previous changes and can be ignored. It does not cause any problems runtime.

**Comment by SystemParadox** [comment]
This causes webmake to fail

**Comment by maritz** [comment]
Fixed.

**Comment by SystemParadox** [comment]
Any chance this change can be published to npm?

Thanks.
