### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by sparkleholic** [maritz/node-sprintf#16]
Hi,
Thank you for providing a good node module.. :+1:

Can I know which license is used on this, BSD or MIT ?

**Comment by maritz** [comment]
You should probably either use the node native built-in util.format() or https://github.com/alexei/sprintf.js.

This project is obsolete.

**Comment by bahamas10** [comment]
I'm in a similar situation... i'm using a module that depends on this module and would also like to know the LICENSE for possible use in a commercial app... MIT would be preferable :) and is arguably the best license... I use it for every module I write.

**Comment by maritz** [comment]
Since this is basically the same thing as alexei/sprintf.js I am forced to use his license.

I would suggest contacting the package maintainer of the module you use that depends on node-sprintf and convince them to change to alexei/sprintf.js.
