### ISSUE TITLE
Add License element to package.json

### ISSUE THREAD

**Issue by HamletDRC** [maritz/node-sprintf#18]
Please add license information to the package.json. 
Documentation is here: https://www.npmjs.org/doc/files/package.json.html

**Comment by maritz** [comment]
What exactly is your usecase for using this package over the sprintf-js package or the build-in?

**Comment by HamletDRC** [comment]
My companies legal department requires us to submit a full list of all our dependencies along with their licenses. Then they review all the licenses and approve the usage. We do this for every release. 

Our build process reads all the package.json files and generates a list of all used dependencies. So I'd like the license element to be available in whatever comes down to disk with an "npm install". It can be in package.json, .package.json, readme.md or license.txt. I know you have some copy/pasted license in your readme, but it does not actually have a declaration of the name of the license, so our legal would need to analyze the wording in your readme. It would be much better for us if there was just an element that said BSD or whatever it is exactly that you're using. Without this declaration we have to assume that you hand-write this license and we have to have our legal team review it. 

As for my usecase about why I use node-sprintf... it is just a transative dependency deep within some other dependency. I have no idea why we use node-sprintf

**Comment by HamletDRC** [comment]
Just for fun, I looked it up. The dependency chain goes like this: 

my app -> react-tools -> commoner -> install -> whiskey -> sprintf

And the sprintf package.json declares this git-repository as the source, and this url as the bug tracker!

**Comment by maritz** [comment]
This whole situation is kind of unfortunate. I mean sure I can add the license thing. But in the end you're still using an unmaintained package. Could you additionally create a ticket for whiskey to change to either use the built-in or sprintf-js?

Also: Since I'm not the copyright holder, I don't think I'm allowed to change the copyright/license text. Thus I can't really slap a label like "BSD" on it.

**Comment by HamletDRC** [comment]
The text within your license file is a BSD 3-clause license: https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29

You don't have to change the license file, just the package.json so it says 
    license: 'BSD'

I'll follow up with Whiskey.

**Comment by maritz** [comment]
Okay, I just looked at the sprintf-js package and he actually has it in his package.json, so I guess I can actually just use it. I would have been very careful about it otherwise.

```
"license": "BSD-3-Clause"
```

**Comment by maritz** [comment]
I will update the version and npm publish as soon as I can.

**Comment by maritz** [comment]
Sorry, had forgotten about this. Published now.
