### ISSUE TITLE
Typo in sprintf README

### ISSUE THREAD

**Issue by mcandre** [maritz/node-sprintf#2]
requrie should be require.

Thanks very much for creating this library and adding it to NPM!

**Comment by maritz** [comment]
Hah, thanks a lot. :)

I was really surprised there was nothing like this in npm when I looked for it.

**Comment by mcandre** [comment]
I'll be offering packages to NPM soon. Is it as easy as "npm publish GITHUB_TARBALLL_LINK"?

**Comment by maritz** [comment]
If you have a valid package.json, yes.

To make sure everything works you should first "npm install ." in a checked-out directory.

(and if you've got that, you might as well just "npm publish ." to publish the current directory. at least that's what i'm doing)

Oh, and you might want to tag your release as stable and/or latest, if that matches your publish. The npm help (man npm) is pretty good!

**Comment by mcandre** [comment]
Thanks man!

http://search.npmjs.org/#/quickcheck
