### ISSUE TITLE
Missing parameters are not handled

### ISSUE THREAD

**Issue by ilyash** [maritz/node-sprintf#20]
```
sprintf = require('sprintf');
console.log(sprintf('%s %s', 'a'));

```

Returns

```
a undefined
```

**Comment by ilyash** [comment]
Should be an exception I guess

**Comment by maritz** [comment]
Is there any specific reason you can't use https://github.com/alexei/sprintf.js ?

**Comment by ilyash** [comment]
Sorry, I've just seen the readme. I initially came here because this library was used in an existing project.
