### ISSUE TITLE
Confusion between sprintf and sprintf-js: Which one is more up to date?

### ISSUE THREAD

**Issue by zodiac403** [maritz/node-sprintf#21]
Hi @maritz 
is there still active maintenance going on for this npm package?

I came into confusion when I tried to **npm install sprintf**, which I used as '**bower_component** some years ago. Now I went with **sprintf-js**, which looks like the newest version of the component I am looking for.

If this package was not actively maintained anymore, a deprecated message in the npm install script would had helped me a lot.

What are your thoughts?

**Comment by maritz** [comment]
Thanks for pointing out the deprecated option in npm itself. While I've seen it in use many times, it did not occur to me to use it here.

To do this I looked at the package on npmjs and I noticed that this package was still the first result in searches for sprintf, even when sorting by maintenance - kinda weird.

I deprecated the package and now it doesn't show up in npmjs searches anymore as well.

Let's hope this package can someday finally be laid to rest.
